import { Livvic } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const livvic = Livvic({ subsets: ["latin"], weight: ["600", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={livvic.className}>
        <div className="mx-[2.4rem] mb-[8rem] mt-[4.8rem]">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
