import { Livvic } from "next/font/google";
import "./globals.css";

const livvic = Livvic({ subsets: ["latin"], weight: ["600", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={livvic.className}>{children}</body>
    </html>
  );
}
